# Generated by Django 5.0.2 on 2024-08-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_livro_autores"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
    ]
